language: cpp

os:
  - linux
  - windows

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.55.5/hugo_0.55.5_Linux-64bit.deb; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i /tmp/hugo.deb                                                                                  ; fi

  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then curl -L -o /tmp/hugo.zip https://github.com/gohugoio/hugo/releases/download/v0.55.5/hugo_0.55.5_Windows-64bit.zip; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cd /tmp/ && unzip hugo.zip                                                                                       ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export PATH=$PATH:/tmp                                                                                           ; fi
  - pwd

script:
  - hugo # This commands builds your website on travis

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  target_branch: gh-pages
